include ../../makefile.master
include ../makefile.langpair
DATASET=test2005
INPUT_SRC=../../../statmt-corpus/test2005/devtest2006.es
INPUT_REF=../../../statmt-corpus/test2005/devtest2006.en
PILOT0_FILE=$(INPUT_REF)
