#!/home/anglistik/robertsw/local-clou/bin/bash

# cat tmp/es_en/europarl-v7.es-en.e/tm_tlemma/tm_data_split/list
# $SGE_TASK_ID
# i is the line of the file
# which file? $(DATA_SPLIT_LIST)
# let's say DATA_SPLIT_LIST=tmp/es_en/europarl-v7.es-en.e/tm_tlemma/tm_data_split/list

#{
if [ $ML_METHOD == maxent ]
then
	PARAMS_BASH="--feature_column $FEAT_COL -f $FEAT_CUT -p 'smooth_sigma $SMOOTH_SIGMA'"
fi
if [ $ML_METHOD == vw ]
then
	PARAMS_BASH="--feature_column $FEAT_COL -w 0.05"
fi

echo "PARAMS_BASH is $PARAMS_BASH"
echo "i=`tail -n+$SGE_TASK_ID $DATA_SPLIT_LIST | head -n1`;"
i=`tail -n+$SGE_TASK_ID $DATA_SPLIT_LIST | head -n1`;
echo "i is $i"
echo "zcat $DATA_SPLIT_DIR/$i | $SCRIPT_DIR/train.pl $ML_METHOD -i $INSTANCES -m $MIN_INSTANCES --min_per_class $MIN_PER_CLASS --class_coverage $CLASS_COVERAGE $PARAMS_BASH $MODEL_SPLIT_DIR/$i;"
zcat $DATA_SPLIT_DIR/$i | $SCRIPT_DIR/train.pl $ML_METHOD -i $INSTANCES -m $MIN_INSTANCES --min_per_class $MIN_PER_CLASS --class_coverage $CLASS_COVERAGE $PARAMS_BASH $MODEL_SPLIT_DIR/$i;
echo "touch $MODEL_SPLIT_DIR/done.$i"
touch $MODEL_SPLIT_DIR/done.$i
#} #2>&1 > $TRAIN_LOG_DIR/$JOB_NAME.o$JOB_ID.$TASK_ID
