include ../../makefile.master
include ../makefile.langpair
DATASET=mwe-test-1
INPUT_SRC=../../../mwe-test-corpus/test1/mwe-test-set.es
INPUT_REF=../../../mwe-test-corpus/test1/mwe-test-set.en
PILOT0_FILE=$(INPUT_REF)
