include ../../makefile.master
include ../makefile.langpair
DATASET=test2007
INPUT_SRC=../../../statmt-corpus/test2007/test2007.en
INPUT_REF=../../../statmt-corpus/test2007/test2007.de
PILOT0_FILE=$(INPUT_REF)
