include ../../makefile.master
include ../makefile.langpair
DATASET=test2008
INPUT_SRC=../../../statmt-corpus/test2008/test2008.en
INPUT_REF=../../../statmt-corpus/test2008/test2008.nl
PILOT0_FILE=$(INPUT_REF)
