include ../../makefile.master
include ../makefile.langpair
DATASET=test2006
INPUT_SRC=../../../statmt-corpus/test2006/test2006.en
INPUT_REF=../../../statmt-corpus/test2006/test2006.es
PILOT0_FILE=$(INPUT_REF)
